--- 
components: 
  schemas: 
    ParkingGroup: 
      $ref: "https://raw.githubusercontent.com/smart-data-models/dataModel.Parking/master/ParkingGroup/schema.yaml#/ParkingGroup"
info: 
  description: ""
  title: ParkingGroup
  version: "1.0.0"
openapi: "3.0.0"

# These paths are merely representative.
paths: 
  /ngsi-ld/v1/entities: 
    get: 
      description: >-
         This entity contains a harmonised description of a generic crop. This entity
         is primarily associated with the agricultural vertical and related IoT
          applications.
      parameters: 
        - 
          in: query
          name: type
          required: true
          schema: 
            enum: 
              - ParkingGroup
            type: string
      responses: 
        ? "200"
        : 
          content: 
            application/ld+json: 
              examples: 
                keyvalues: 
                  summary: "Key-Values Pairs"
                  value: 
                    - 
                      $ref: "https://raw.githubusercontent.com/smart-data-models/dataModel.Parking/master/ParkingGroup/example.json"
                normalized: 
                  summary: "Normalized NGSI-LD"
                  value: 
                    - 
                      $ref: "https://raw.githubusercontent.com/smart-data-models/dataModel.Parking/master/ParkingGroup/example-normalized-ld.jsonld"
          description: OK
      tags: 
        - ngsi-ld
tags: 
  - 
  
    description: "NGSI-LD Linked-data Format"
    name: ngsi-ld
