--- 
components: 
  schemas: 
    OffStreetParking: 
      $ref: "https://raw.githubusercontent.com/smart-data-models/dataModel.Parking/master/OffStreetParking/schema.yaml#/OffStreetParking"
info: 
  description: ""
  title: OffStreetParking
  version: "1.0.0"
openapi: "3.0.0"

# These paths are merely representative.
paths: 
  /ngsi-ld/v1/entities: 
    get: 
      description: "Off street parking"
      parameters: 
        - 
          in: query
          name: type
          required: true
          schema: 
            enum: 
              - OffStreetParking
            type: string
      responses: 
        ? "200"
        : 
          content: 
            application/ld+json: 
              examples: 
                keyvalues: 
                  summary: "Key-Values Pairs"
                  value: 
                    - 
                      $ref: "https://raw.githubusercontent.com/smart-data-models/dataModel.Parking/master/OffStreetParking/example.json"
                normalized: 
                  summary: "Normalized NGSI-LD"
                  value: 
                    - 
                      $ref: "https://raw.githubusercontent.com/smart-data-models/dataModel.Parking/master/OffStreetParking/example-normalized-ld.jsonld"
          description: OK
      tags: 
        - ngsi-ld
tags: 
  - 
  
    description: "NGSI-LD Linked-data Format"
    name: ngsi-ld
