--- 
components: 
  schemas: 
    ParkingAccess: 
      $ref: "https://raw.githubusercontent.com/smart-data-models/dataModel.Parking/master/ParkingAccess/schema.yaml#/ParkingAccess"
info: 
  description: "'Parking Access - TODO: Provide a complete Schema'"
  title: ParkingAccess
  version: "1.0.0"
openapi: "3.0.0"

# These paths are merely representative.
paths: 
  /ngsi-ld/v1/entities: 
    get: 
      description: "Retrieve a set of entities which matches a specific query from an NGSI-LD system"
      parameters: 
        - 
          in: query
          name: type
          required: true
          schema: 
            enum: 
              - OnStreetParking
            type: string
      responses: 
        ? "200"
        : 
          content: 
            application/ld+json: 
              examples: 
                keyvalues: 
                  summary: "Key-Values Pairs"
                  value: 
                    - 
                      $ref: "https://raw.githubusercontent.com/smart-data-models/dataModel.Parking/master/ParkingAccess/example.json"
                normalized: 
                  summary: "Normalized NGSI-LD"
                  value: 
                    - 
                      $ref: "https://raw.githubusercontent.com/smart-data-models/dataModel.Parking/master/ParkingAccess/example-normalized-ld.jsonld"
          description: OK
      tags: 
        - ngsi-ld
tags: 
  - 
  
    description: "NGSI-LD Linked-data Format"
    name: ngsi-ld
